stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mongo:v2
      pushRemote: true
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
        exclude:
        - cluster-10-test
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./mongo_service.yml
  - applyYamlConfig:
      path: ./mongo-statefulset.yaml
timeout: 600
notification: {}
