stages:
- name: 'build '
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mongo:v1
      pushRemote: true
      registry: 10.0.8.59:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./pv.yaml
  - applyYamlConfig:
      path: ./mongo-statefulset.yaml
  - applyYamlConfig:
      path: ./mongo_service.yml
timeout: 60
notification: {}
