stages:
- name: 'build '
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mongo:v2
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: /pv.yaml
  - applyYamlConfig:
      path: /mongo-statefulset.yaml
timeout: 600
notification: {}
