apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: fiware
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: csp2-centos-1:5000/fiware-mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017
          readinessProbe:
           exec :
             command:
             - bash
             - "-c"          
             - |
               set -ex  
               mongo --eval "rs.initiate({_id: 'rs0',members: [{_id: 0, host: 'mongo-0.mongo.ceph.svc.cluster.local:27017'},{_id: 1, host: 'mongo-1.mongo.ceph.svc.cluster.local:27017'},{_id: 2, host: 'mongo-2.mongo.ceph.svc.cluster.local:27017'}]})";
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      storageClassName: "mongo-sc"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
