---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: csp2-centos-1:5000/mongo:v2
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017
          readinessProbe:
           exec :
             command:
             - bash
             - "-c"          
             - |
               set -ex  
               mongo --eval "rs.initiate({_id: 'rs0',members: [{_id: 0, host: 'mongo-0.mongo:27017'},{_id: 1, host: 'mongo-1.mongo:27017'},{_id: 2, host: 'mongo-2.mongo:27017'}]})";
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/mongo_db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      storageClassName: "manual"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi
