apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiwaremongo-pv01-ppln
  labels: 
    type: local 
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /var/nfs/dev_area/pipeline-pv1 
    server: 192.168.100.176 
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiwaremongo-pv02-ppln
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/dev_area/pipeline-pv2
    server: 192.168.100.176
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiwaremongo-pv03-ppln
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/dev_area/pipeline-pv3
    server:  192.168.100.176
    readOnly: false
