apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiwaremongo-pv01
  labels: 
    type: local 
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /var/nfs/fiware/pv01 
    server: 192.168.100.176 
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiwaremongo-pv02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/fiware/pv02
    server: 192.168.100.176
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiwaremongo-pv03
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/fiware/pv03
    server:  192.168.100.176
    readOnly: false